export default {
  // BASE
  SET_ERROR: 'SET_ERROR',

  // User
  SET_USER: 'SET_USER',
  SET_USER_SWITCH: 'SET_USER_SWITCH',
  SET_USER_TWITELO_SWITCH: 'SET_USER_TWITELO_SWITCH',
  SET_USER_LANG: 'SET_USER_LANG',
  SET_TWITELO_DATA: 'SET_TWITELO_DATA',
  SET_TWITELO_DATA_CONTENT: 'SET_TWITELO_DATA_CONTENT',

  // BUILDER
  SET_GAMES: 'SET_GAMES',
  SET_USER_TAGS: 'SET_USER_TAGS',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  SET_ACCOUNT_SETTINGS: 'SET_ACCOUNT_SETTINGS',
  SET_ALL_ACCOUNTS: 'SET_ALL_ACCOUNTS',
  SET_USER_TAG_NOT_INCLUDED: 'SET_USER_TAG_NOT_INCLUDED',
  SET_USER_TAG_INCLUDED: 'SET_USER_TAG_INCLUDED',
  SET_TWITELO_DATA_INPUT: 'SET_TWITELO_DATA_INPUT',
  SET_TWITELO_DATA_INPUT_ALL: 'SET_TWITELO_DATA_INPUT_ALL',
  SET_TEXT_COUNTER: 'SET_TEXT_COUNTER',
  SET_PREVIEW_DATA: 'SET_PREVIEW_DATA',
  SET_BUILDER_LOADING: 'SET_BUILDER_LOADING',
  SET_PREVIEW_PROFILE: 'SET_PREVIEW_PROFILE',
  SET_SELECTED_GAME: 'SET_SELECTED_GAME',
  SET_GAME_TAGS_CATEGORY: 'SET_GAME_TAGS_CATEGORY',
  SET_GAME_TAGS_CATEGORY_PAGES: 'SET_GAME_TAGS_CATEGORY_PAGES',
  DELETE_USER_TAGS: 'DELETE_USER_TAGS',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  ADD_USER_TAG: 'ADD_USER_TAG',
};
