export default {
  // BASE
  SET_ERROR: 'SET_ERROR',

  // User
  SET_USER: 'SET_USER',
  SET_USER_SWITCH: 'SET_USER_SWITCH',
  SET_USER_LANG: 'SET_USER_LANG',

  // BUILDER
  SET_GAMES: 'SET_GAMES',
  SET_USER_TAGS: 'SET_USER_TAGS',
  SET_ACCOUNT_SETTINGS: 'SET_ACCOUNT_SETTINGS',
  SET_ALL_ACCOUNTS: 'SET_ALL_ACCOUNTS',
  SET_USER_TAG_NOT_INCLUDED: 'SET_USER_TAG_NOT_INCLUDED',
  SET_USER_TAG_INCLUDED: 'SET_USER_TAG_INCLUDED',
  SET_TWITELO_DATA_INPUT: 'SET_TWITELO_DATA_INPUT',
  SET_TWITELO_DATA_INPUT_ALL: 'SET_TWITELO_DATA_INPUT_ALL',
};
